import os
import stat
from pathlib import Path

from autodoc.utils.logger import setup_logger

logger = setup_logger()


def init_project():
    """
    Installs the git hook in the current repository.
    """
    hook_path = Path(".git/hooks/post-commit")

    if not Path(".git").exists():
        logger.error("Not a git repository. Run 'git init' first.")
        return

    logger.info(f"Installing post-commit hook to {hook_path}...")

    # We assume 'autodoc' is installed in the python environment where git calls this.
    # The hook script itself acts as the entry point.
    hook_content = """#!/usr/bin/env python3
# Auto-Doc Hook
# Generated by 'autodoc init'

import sys
try:
    from autodoc.hooks.post_commit import main
except ImportError:
    print("❌ Auto-Doc not found in python environment.")
    print("Please ensure 'autodoc' is installed in the active python environment.")
    sys.exit(0)

if __name__ == "__main__":
    main()
"""

    try:
        hook_path.write_text(hook_content, encoding="utf-8")
        # Make executable
        st = os.stat(hook_path)
        os.chmod(hook_path, st.st_mode | stat.S_IEXEC)
        logger.info("✅ Hook installed successfully.")
    except Exception as e:
        logger.error(f"Failed to install hook: {e}")
