import importlib.resources
import os
import stat
from pathlib import Path

from autodoc.utils.logger import setup_logger

logger = setup_logger()


def init_project():
    """
    Installs the git hook in the current repository.
    """
    hook_path = Path(".git/hooks/post-commit")

    if not Path(".git").exists():
        logger.error("Not a git repository. Run 'git init' first.")
        return

    logger.info(f"Installing post-commit hook to {hook_path}...")

    # We assume 'autodoc' is installed in the python environment where git calls this.
    # The hook script itself acts as the entry point.
    hook_content = """#!/usr/bin/env python3
# Auto-Doc Hook
# Generated by 'autodoc init'

import sys
try:
    from autodoc.hooks.post_commit import main
except ImportError:
    print("❌ Auto-Doc not found in python environment.")
    print("Please ensure 'autodoc' is installed in the active python environment.")
    sys.exit(0)

if __name__ == "__main__":
    main()
"""

    try:
        hook_path.write_text(hook_content, encoding="utf-8")
        # Make executable
        st = os.stat(hook_path)
        os.chmod(hook_path, st.st_mode | stat.S_IEXEC)
        logger.info("✅ Hook installed successfully.")
    except Exception as e:
        logger.error(f"Failed to install hook: {e}")

    # 2. Create Default Templates
    templates_dir = Path(".autodoc/templates")
    templates_dir.mkdir(parents=True, exist_ok=True)

    # A. System Instruction
    sys_path = templates_dir / "system_instruction.j2"
    if not sys_path.exists():
        content = _get_package_template("system_instruction.j2")
        sys_path.write_text(content, encoding="utf-8")

    # B. Doc Prompt
    prompt_path = templates_dir / "doc_prompt.j2"
    if not prompt_path.exists():
        # Map default_prompt.j2 (internal) to doc_prompt.j2 (user)
        content = _get_package_template("default_prompt.j2")
        prompt_path.write_text(content, encoding="utf-8")

    # 3. Create Default Config
    config_path = Path(".autodoc/config.yaml")

    if not config_path.exists():
        logger.info(f"Creating default config at {config_path}...")
        config_content = """# Auto-Doc Configuration

# Global Context
context:
  files:
    - "README.md"

# Mappings: source globs -> target docs
mappings:
  - name: "Main API"
    source: "src/**/*.py"
    doc: "docs/reference.md"

# Templates
# Paths to your custom Jinja2 templates
prompt_template: ".autodoc/templates/doc_prompt.j2"
system_instruction_template: ".autodoc/templates/system_instruction.j2"

# Model Configuration
model: "gemini-3-flash-preview"
thinking_level: "high"
"""
        try:
            config_path.write_text(config_content, encoding="utf-8")
            logger.info("✅ Config created successfully.")
        except Exception as e:
            logger.error(f"Failed to create config: {e}")
    else:
        logger.info(f"ℹ️  Config file already exists at {config_path}")


def _get_package_template(name: str) -> str:
    """Retrieves content of a template file from the package source."""
    try:
        # Modern python >= 3.9
        ref = importlib.resources.files("autodoc.templates") / name
        return ref.read_text(encoding="utf-8")
    except Exception as e:
        logger.warning(f"Failed to load package template {name} via importlib: {e}")
        # Fallback for dev mode
        base_dir = Path(__file__).resolve().parent.parent / "templates"
        template_path = base_dir / name
        if template_path.exists():
            return template_path.read_text(encoding="utf-8")
        return f"# Error loading template: {name}"
